<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\InventoryInStorePickupApi\Api\Data;

/**
 * @TODO Replace with autogenerated immutable realization.
 */
interface PickupLocationInterface
{
    const IN_STORE_PICKUP_CODE = 'is_pickup_location_active';
}
