<?php
/**
 * Copyright 2019 Adobe
 * All Rights Reserved.
 */

// phpcs:disable Generic.Files.LineLength.TooLong
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "triggerShippingMethodUpdate": {
                        "component": "Magento_InventoryInStorePickupSalesAdminUi/order/create/trigger-shipping-method-update"
                    }
                }
            }
        }
    }
</script>
